api/urls.py
from rest_framework.urlpatterns import format_suffix_patterns
from django.urls import path, re_path
from .views import PostList, PostDetail

app_name = "api"

urlpatterns = [
    path('', PostList.as_view(), name="api_bloglist"),
    path('post/<int:pk>/', PostDetail.as_view(), name="api_blogdetail"),
]

urlpatterns = format_suffix_patterns(urlpatterns)

blog/urls.py
from django.urls import path, re_path
from . import views

app_name = "blog"

urlpatterns = [
    path('search/', views.blog_search, name="blog_search"),
    path('categories/', views.get_categories, name="blog_categories"),
    path('my-blogs/', views.my_blogs, name="my_blogs"),
    path('new-blog-post/', views.write_new_blog, name="write_new_blog"),
    path('new-blog-post-preview/', views.save_blog_and_show_preview, name="save_blog_and_show_preview"),
    # path('blog/submit-for-moderation/', views.submit_blog_for_moderation, name="submit_blog_for_moderation"),
    path('blog-tags/', views.blog_tags, name="blog_tags"),
    re_path(r'^edit-blog-post/(?P<id>[\d]+)/(?P<slug>[\w\d-]+)/$', views.edit_blog, name="edit_blog_post"),
    #
    re_path(r'ajax/bookmark/(?P<id>[\d]+)$', views.bookmark_blogpost, name="bookmark_blogpost"),
    re_path(r'ajax/like/(?P<id>[\d]+)$', views.like_blogpost, name="like_blogpost"),
    re_path(r'ajax/blog-request/(?P<category_id>[\d]+)$', views.blog_request, name="blog_request"),
    re_path(r'^ajax/submit-for-moderation-preview/$', views.submit_for_moderation, name="submit_for_moderation"),
    #
    re_path(r'^(?P<id>[\d]+)/(?P<slug>[\w\d-]+)/$', views.blog_detail, name="blog_detail"),
    re_path(r'^draft/(?P<id>[\d]+)/(?P<slug>[\w\d-]+)/$', views.draft_blog_detail, name="draft_blog_detail"),
    re_path(r'^awaiting-moderation/(?P<id>[\d]+)/(?P<slug>[\w\d-]+)/$', views.awaiting_moderation_blog_detail, name="awaiting_moderation"),
    re_path(r'^preview/(?P<id>[\d]+)/(?P<blog_slug>[\w\d-]+)/$', views.preview_blog, name="preview_blog"),
    # re_path(r'^preview/from-edit-blog/$', views.preview_from_edit_blog, name="preview_from_edit_blog"),
    #
    re_path(r'^filter-by-category/(?P<category_slug>[\w\d-]+)$', views.filter_by_category, name="filter_by_category"),
    re_path(r'^filter-by-tag/(?P<slug>[\w\d-]+)$', views.filter_by_tag, name="filter_by_tag"),
    re_path(r'^filter-by-author/(?P<id>[\d]+)$', views.filter_by_author, name="filter_by_author"),
    #
    re_path(r'^accept-and-publish/blog/(?P<id>[\d]+)/$', views.accept_and_publish, name="accept_and_publish"),
]

user/urls.py
from django.urls import path, re_path
from . import views

app_name = "user"

urlpatterns = [
    path('', views.index, name="index"),
    path('about-us/', views.about, name="about_us"),
    re_path(r'^drafts/$', views.user_drafts, name="user_drafts"),
    re_path(r'^ajax/follow-author/$',  views.follow, name="follow_author"),
    path('interests/', views.user_interests, name="user_interests"),
    path('page-not-found', views.pagenotfound, name="pagenotfound"),
    path('dashboard/', views.user_dashboard, name="user_dashboard"),
    path('ajax/get-user-info/', views.get_user_information, name="get_user_information"),
    path('ajax/unfollow-author/', views.unfollow_author, name="unfollow_author"),
    path('ajax/get-all-tags/', views.get_all_tags, name="get_all_tags"),
    path('ajax/add-new-tag/', views.add_new_tag, name="add_new_tag"),
    path('ajax/mark-as-read/', views.mark_as_read, name="mark_as_read"),
    path('moderator-dashboard/', views.moderator_dashboard, name="moderator_dashboard"),
    path('notifications/', views.notifications, name="notifications")
]

blog/forms.py
from django import forms
from blog.models import BlogPost, Category
from ckeditor_uploader.widgets import CKEditorUploadingWidget
from django.conf import settings
from PIL import Image
from toolbelt.utils import (
    get_user_directory_thumbnail_path,
    )


class BlogPostForm(forms.ModelForm):
    blog_title = forms.CharField(widget=forms.TextInput(attrs={"class": "save"}))
    blog_subtitle = forms.CharField(widget=forms.TextInput(attrs={"class": "save"}))
    banner_image_source = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Ex: Picture taken by @JohnDoe", "class": "save"}))
    content = forms.CharField(widget=CKEditorUploadingWidget())
    blog_category = forms.ChoiceField(widget=forms.Select(attrs={"class": "save"}), choices=[(cat.id, cat.category_name) for cat in Category.objects.all()])
    blog_tags = forms.CharField(widget=forms.TextInput(attrs={"data-role": "tagsinput", "class": "form-control"}))

    class Meta:
        model = BlogPost
        widgets = {
            'banner_image': forms.ClearableFileInput(attrs={'class': 'save', 'required': 'required'}),
        }
        exclude = ('blog_author', 'blog_slug', 'created_on', 'updated_on', 'moderator_accepted', 'published', 'draft', 'preview')

    def clean_blog_category(self):
        category = self.cleaned_data["blog_category"]
        try:
            category = Category.objects.get(id=category)
            return category
        except Exception:
            return None

    def clean_blog_tags(self):
        blog_tags = self.cleaned_data["blog_tags"]
        if len(blog_tags) > 0:
            blog_tags = blog_tags.split(",")
            return blog_tags


class BlogEditForm(BlogPostForm):
    class Meta:
        model = BlogPost
        widgets = {
        'banner_image': forms.ClearableFileInput(attrs={'class': 'save'}),
        }
        exclude = ('blog_author', 'blog_slug', 'created_on', 'updated_on', 'moderator_accepted', 'published', 'draft', 'preview')


    def clean_blog_category(self):
        category = self.cleaned_data["blog_category"]
        try:
            category = Category.objects.get(id=category)
            return category
        except Exception:
            return None

    def clean_blog_tags(self):
        blog_tags = self.cleaned_data["blog_tags"]
        if len(blog_tags) > 0:
            blog_tags = blog_tags.split(",")
            return blog_tags

blog/views.py
import re
import json
import datetime

from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required

from django.http import JsonResponse
from django.contrib import messages
from django.contrib.auth.models import User, Group
from django.utils.text import slugify
from django.urls import reverse
from taggit.models import Tag

from .models import BlogPost, Category, BlogRequest, MyCustomTag
from .forms import BlogPostForm, BlogEditForm
from user.models import Profile, UserBookmarks, UserFollowing, UserLikes, Notifications


# views here
def blog_search(request):
    if request.method == "POST":
        context = {}
        try:
            # get blog titles with search term.
            search_text = request.POST.get('blogsearch')

            # validation
            pattern = re.compile("[@_!#$%^&*()<>?/\\|}{~:]")

            if pattern.search(search_text) is not None:
                messages.error(request, "No Speacial Characters Are Allowed.")
                return render(request, "blog/search-results.html", context={"messages": messages})
            else:
                blogs = BlogPost.objects.filter(
                    blog_title__icontains=search_text)
                if len(blogs) > 0:
                    context['blogs'] = blogs
                else:
                    context['no_results'] = "no_results"
                return render(request, "blog/search-results.html", context)
        except Exception:
            return render(request, "blog/search-results.html", context={"no_results": "no_results"})
    else:
        search = True
        return render(request, "blog/search-results.html", context={"search": search})


@login_required
def preview_blog(request, id, blog_slug):
    author_group = Group.objects.get(name='author')
    moderator_group = Group.objects.get(name='moderator')

    if (request.user.groups.filter(name=author_group).exists()) or (request.user.groups.filter(name=moderator_group).exists()):
        if id and blog_slug:
            try:
                preview_blog = BlogPost.objects.get(
                    id=id, blog_slug=blog_slug, preview=True)
                context = {"blog": preview_blog}

                if preview_blog.submitted_for_moderation is True:
                    context["submitted_for_moderation"] = True
                else:
                    context["submitted_for_moderation"] = False
                    # STOPPED HERE. WRITE BLOG -> PREVIEW -> PREVIEW FROM NEW BLOG
                    # -> EDIT -> EDIT BLOG -> PREVIEW -> PREVIEW BLOG (Check mod submission)

                if request.user.groups.filter(name=moderator_group).exists():
                    context["is_moderator"] = True
                else:
                    context["is_moderator"] = False

                return render(request, "blog/preview_blog.html", context)
            except BlogPost.DoesNotExist as e:
                if e:
                    return render(request, "pagenotfound.html")
        else:
            return redirect("user:pagenotfound")
    else:
        return redirect("user:pagenotfound")


# writing new blog
@login_required
def write_new_blog(request):
    author_group = Group.objects.get(name='author')
    moderator_group = Group.objects.get(name='moderator')
    if request.user.groups.filter(name=author_group).exists() or request.user.groups.filter(name=moderator_group).exists():
        # Check if user is permitted to access this page. Else redirect to 404.
        new_blog_form = BlogPostForm()
        userProfile = Profile.objects.get(user=request.user)

        context = {
            "new_blog_form": new_blog_form,
            "user_profile": userProfile
        }

        return render(request, "blog/write_blog.html", context)
    else:
        return redirect("user:pagenotfound")


def blog_tags(request):
    tags = [tag.name for tag in Tag.objects.all()]
    return tags


@login_required
def save_blog_and_show_preview(request):
    author_group = Group.objects.get(name='author')
    moderator_group = Group.objects.get(name='moderator')
    if request.user.groups.filter(name=author_group).exists() or request.user.groups.filter(name=moderator_group).exists():
        if request.method == "POST":
            blogpostform = BlogPostForm(request.POST, request.FILES)

            if blogpostform.is_valid():
                blog_post = blogpostform.save(commit=False)
                blog_post.preview = True
                blog_post.draft = True
                blog_post.blog_author = request.user
                blog_post.save()
                # for tags to save use 'save_m2m'
                blogpostform.save_m2m()
                messages.success(
                    request, "Your blog is now saved as draft, check your drafts to publish.")
                return redirect("blog:preview_blog", id=blog_post.id, blog_slug=blog_post.blog_slug)
            else:
                messages.error(
                    request, "Something went wrong. Please make sure all fields are valid.")
                return redirect("blog:write_new_blog")
        else:
            return redirect("blog:write_new_blog")
    else:
        return redirect("user:pagenotfound")


@login_required
def edit_blog(request, id, slug):
    author_group = Group.objects.get(name='author')
    moderator_group = Group.objects.get(name='moderator')
    if request.user.groups.filter(name=author_group).exists() or request.user.groups.filter(name=moderator_group).exists():
        post = get_object_or_404(BlogPost, pk=id)

        try:
            post = BlogPost.objects.get(pk=id)
        except BlogPost.DoesNotExist:
            return redirect("user:pagenotfound")

        if post.blog_author == request.user:
            if request.method == "POST":
                form = BlogEditForm(request.POST, request.FILES, instance=post)
                if form.is_valid():
                    post = form.save(commit=False)
                    post.preview = True
                    post.draft = True
                    post.moderator_accepted = False
                    post.published = False
                    post.save()
                    # for tags to save use 'save_m2m'
                    form.save_m2m()
                    messages.success(
                        request, "Your blog is successfully updated.")
                    return redirect("blog:preview_blog", id=post.id, blog_slug=post.blog_slug)
                else:
                    return redirect("blog:preview_blog", id=post.id, blog_slug=post.blog_slug)

            else:
                edit_form = BlogEditForm(instance=post)
                return render(request, "blog/edit_blog.html", context={"edit_form": edit_form, "post": post})
        else:
            return redirect("user:pagenotfound")


def bookmark_blogpost(request, id):
    if request.user.is_authenticated:
        # Add this blog to bookmark table.
        blog_post = BlogPost.objects.get(id=id)
        # check if bookmarked already
        bookmark_status = 0

        try:
            bookmark_check = UserBookmarks.objects.filter(
                user=request.user, blog_post=blog_post)
            if len(bookmark_check) > 0:
                bookmark_status = 0
                bookmark_check.delete()
            else:
                bookmark = UserBookmarks.objects.create(
                    user=request.user, blog_post=blog_post)
                bookmark.save()
                bookmark_status = 1

                # Add to notification
                notification = Notifications.objects.create(
                    user=request.user,
                    title="{} has bookmarked your blog post.".format(
                        request.user.username),
                    url=reverse("blog:blog_detail", kwargs={
                                "id": bookmark.blog_post.id, "slug": bookmark.blog_post.blog_slug}),
                    notify=bookmark.blog_post.blog_author
                )
                notification.save()
        except Exception as e:
            if e:
                bookmark_status = 0
        return render(request, "blog/ajax/bookmark.html", context={'blog_post': blog_post, 'bookmark_status': bookmark_status})
    else:
        # redirect them to login page, with ?next to current blog they want.
        return JsonResponse({"error": "Sorry something went wrong. Please try later.", "authenticated": False}, status=300)


def like_blogpost(request, id):
    if request.user.is_authenticated:
        # Add this blog to user likes table.
        blog_post = BlogPost.objects.get(id=id)

        try:
            like_check = UserLikes.objects.filter(
                user=request.user, blog=blog_post)
            like_status = False
            likes_count = None

            if len(like_check) > 0:
                # if already liked, then unlike it using FALSE.
                # Else Like it using TRUE
                if like_check[0].status is True:
                    like_check[0].status = False
                    like_check[0].save()
                    likes_count = UserLikes.objects.filter(
                        blog=blog_post, status=True).count()
                    like_status = like_check[0].status
                else:
                    like_check[0].status = True
                    like_check[0].save()
                    try:
                        notification = Notifications.objects.get(
                            user=request.user,
                            url=reverse("blog:blog_detail", kwargs={
                                        "id": blog_post.id, "slug": blog_post.blog_slug}),
                            notify=blog_post.blog_author
                        )
                        notification.read = False
                        notification.created_on = datetime.datetime.now()
                        notification.save()

blog/templates/blog/awaiting_moderation_edit_blog.html
{% extends "base.html" %}
{% load static customtags crispy_forms_tags %}

{% block extra_head %}
<link rel="stylesheet" href="{% static 'css/toast.min.css' %}">
<link rel="stylesheet" href="https://cdn.metroui.org.ua/v4/css/metro-colors.min.css">
<link rel="stylesheet"
href="//cdn.jsdelivr.net/gh/highlightjs/cdn-release@10.1.2/build/styles/dracula.min.css">
{% endblock %}

{% block home_banner %} {% endblock %}

{% block content %}
<div class="modal fade" id="tagModal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">New Blog Tag</h5>
		<button type="button" class="close" data-dismiss="modal" aria-label="Close">
        	<span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <span class="error-message" id="newTagErrorSpan" style="display:none;"></span>
          <form class="newTagForm" action="">
              {% csrf_token %}
              <input type="text" name="newTag" class="form-control" value="" placeholder="Add New Tag Here..." id="newTagInputValue" required/>
          </form>
      </div>
      <div class="modal-footer">
  		<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary" id="finishNewTagBtn">Finish</button>
      </div>
    </div>
  </div>
</div>


<div class="container oc-screen newblog-container">
  <div class="row">
    <div class="col-md-8 mx-auto">
      <h1 class="text-center">Edit Blog Post</h1>
      <form method="post" name="editPostForm" id="editPostForm" enctype="multipart/form-data">
          {% csrf_token %}
          {{ edit_blog_form.media }}
          <fieldset>
            <!-- <legend>Legend</legend> -->
            <div class="form-group">
              {{ edit_blog_form.blog_title|as_crispy_field }}
            </div>
            <div class="form-group">
              {{ edit_blog_form.blog_subtitle|as_crispy_field }}
            </div>
            <div class="form-group">
              {{ edit_blog_form.banner_image }}
            </div>
            <div class="form-group">
              {{ edit_blog_form.banner_image_source|as_crispy_field }}
              <small id="banner_image_source_help" class="form-text text-muted">Please mention credits for banner image you are using if it is licensed.</small>
            </div>
            <div class="form-group">
              {{ edit_blog_form.content|as_crispy_field }}
            </div>

            <input type="hidden" name="type" id="type" value="">

            <div class="form-group">
              {{ edit_blog_form.blog_category|as_crispy_field }}
            </div>

            <div class="col-* alert alert-dark">
                <h4> <i class="fa fa-gears"></i> Actions</h4>
                <button type="button" class="btn btn-warning" id="editPreviewBlog"><i class="fa fa-eye"></i> Preview &amp; Submit</button>
                <button type="button" class="btn btn-primary" id="addNewTagBtn" data-toggle="modal" data-target="#tagModal"><i class="fa fa-plus"></i> New Tag</button>
            </div>
          </fieldset>
      </form>
    </div>
  </div>
</div>
<div id="tags" style="display:none;"></div>

{% endblock %}

{% block extra_js %}
<script src="https://cdn.metroui.org.ua/v4/js/metro.min.js"></script>

<script type="text/javascript">

function taginput() {
  $.ajax({
      url: "{% url 'user:get_all_tags' %}",
      dataType: "html",
      data: {"csrfmiddlewaretoken": "{{csrf_token}}"},
      type: "POST",
      success: function(result) {
          $("#blogTagsDiv").html(result);
      }
  });
}

$("#finishNewTagBtn").on("click", function(e) {
    e.preventDefault();

    var newTag = $("#newTagInputValue").val();
    if(newTag.length == 0) {
        $("#newTagErrorSpan").attr("class", "error-message")
        $("#newTagErrorSpan").text("Tag Cannot Be Empty.")
        $("#newTagErrorSpan").show();
        // $("#tagModal").modal("show");
    } else {
        $.ajax({
            url: "{% url 'user:add_new_tag' %}",
            dataType: "json",
            type: "POST",
            data: {"csrfmiddlewaretoken": "{{csrf_token}}", "new_tag": newTag},
            success: function(result) {
                if(result.status == "success") {
                    $("#newTagErrorSpan").attr("class", "success-message")
                    $("#newTagErrorSpan").text("Added new tag successfully");
                    $("#newTagErrorSpan").show();
                    for(i=0; i<result.tags.length; i++) {
                        $("#id_blog_tags").append("<option value='"+result["tags"][i][0]+"'>"+result["tags"][i][1]+"</option>");
                    }
                } else {
                    $("#newTagErrorSpan").attr("class", "error-message")
                    $("#newTagErrorSpan").text("Something went wrong");
                    $("#newTagErrorSpan").show();
                }
            }
        });
    }
});

$("#editPreviewBlog").on("click", function(event) {
  event.preventDefault();

  $("#editPostForm").attr("action", "{% url 'blog:edit_blog_post' id=edit_blog_post.id blog_slug=edit_blog_post.blog_slug %}");
  $("#editPostForm #type").val("preview");
  $("#editPostForm").submit();

});


// $("#draftBtn").on("click", function() {
//   event.preventDefault();
//
//   $("#newBlogForm").attr("action", "{% url 'blog:write_blog' %}");
//   $("#newBlogForm #type").val("draft");
//   $("#newBlogForm").submit();
// });

$("#submitForModerationEdit").on("click", function() {
  event.preventDefault();
  $("#editPostForm").attr("action", "{% url 'blog:write_blog' %}");
  $("#editPostForm #type").val("submitForModeration");
  $("#editPostForm").submit();
});
</script>
{% endblock %}

blog/templates/blog/categories.html
{% extends "base.html" %}
{% load static %}

{% block title %} Categories {% endblock %}

{% block home_banner %}{% endblock %}

{% block content %}
<div class="container-fluid allblogs-div">
  <div class="container">
    <div class="oc-screen">
      {% if messages %}
        <div class="row">
          <div class="col-md-6 mx-auto">
            {% for msg in messages %}
            <div class="alert alert-{{msg.level_tag}} custom-messages" role="alert">
                {{msg.message}}
            </div>
            {% endfor %}
          </div>
        </div>
      {% endif %}
      <div class="row">
        <div class="col-md-6 mx-auto">
          <h1 class="text-center">Blog Categories</h1>
        </div>
      </div>
      <div class="row equal content-container categories-list-div">
        {% for category in categories %}
        <div class="col-md-4 col-sm-6 col-12 d-flex">
          <div class="card mb-3 categories-cards" style="padding:0px">
            <a href="{% url 'blog:filter_by_category' category_slug=category.category_slug %}">
              <img style="height: 200px; width: 100%; display: block;" src="{{category.category_image.url}}" alt="Card image" class="img-responsive">
              <h3 class="card-header">{{category.category_name}}</h3>
              <div class="card-body">
                <p>{{category.category_line}}</p>
              </div>
            </a>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

blog/templates/blog/edit_blog.html
{% extends "base.html" %}
{% load static customtags crispy_forms_tags %}

{% block title %}
{{ edit_form.blog_title }}
{% endblock %}

{% block extra_head %}
<link rel="stylesheet" href="{% static 'css/toast.min.css' %}">
<link rel="stylesheet" href="https://cdn.metroui.org.ua/v4/css/metro-colors.min.css">
<link rel="stylesheet"
href="//cdn.jsdelivr.net/gh/highlightjs/cdn-release@10.1.2/build/styles/dracula.min.css">
<link rel="stylesheet" href="{% static 'css/tagsinput.css' %}">
{% endblock %}

{% block home_banner %} {% endblock %}

{% block content %}
<div class="modal fade" id="tagModal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">New Blog Tag</h5>
		<button type="button" class="close" data-dismiss="modal" aria-label="Close">
        	<span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <span class="error-message" id="newTagErrorSpan" style="display:none;"></span>
          <form class="newTagForm" action="">
              {% csrf_token %}
              <input type="text" name="newTag" class="form-control" value="" placeholder="Add New Tag Here..." id="newTagInputValue" required/>
          </form>
      </div>
      <div class="modal-footer">
  		<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary" id="finishNewTagBtn">Finish</button>
      </div>
    </div>
  </div>
</div>


<div class="container oc-screen newblog-container">
  <div class="row">
    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}
    
    <div class="col-md-8 mx-auto">
      <h1 class="text-center">Edit Blog Post</h1>
      <form method="post" name="editPostForm" action="{% url 'blog:edit_blog_post' id=post.id slug=post.blog_slug %}" id="editPostForm" enctype="multipart/form-data">
          {% csrf_token %}
          {{ edit_form.media }}
          <fieldset>
            <!-- <legend>Legend</legend> -->
            <div class="form-group">
              {{ edit_form.blog_title|as_crispy_field }}
            </div>
            <div class="form-group">
              {{ edit_form.blog_subtitle|as_crispy_field }}
            </div>
            <div class="form-group">
              {{ edit_form.banner_image }}
            </div>
            <div class="form-group">
              {{ edit_form.banner_image_source|as_crispy_field }}
              <small id="banner_image_source_help" class="form-text text-muted">Please mention credits for banner image you are using if it is licensed.</small>
            </div>
            <div class="form-group">
              {{ edit_form.content|as_crispy_field }}
            </div>

            <input type="hidden" name="type" id="type" value="">

            <div class="form-group">
              {{ edit_form.blog_category|as_crispy_field }}
            </div>

            <div class="form-group">
              <input type="text" name="blog_tags" class="form-control" data-role="tagsinput" required id="id_blog_tags" value="{{edit_form.blog_tags.value|get_tags}}">
            </div>

            <div class="col-* alert alert-dark">
                <h4> <i class="fa fa-gears"></i> Actions</h4>
                {% if submitted_for_moderation or is_moderator %}
                <button type="submit" class="btn btn-success" id=""><i class="fa fa-eye"></i> Preview &amp; Save</button>
                {% else %}
                <button type="submit" class="btn btn-warning" id=""><i class="fa fa-eye"></i> Preview &amp; Submit</button>
                {% endif %}
                <!-- <button type="button" class="btn btn-primary" id="addNewTagBtn" data-toggle="modal" data-target="#tagModal"><i class="fa fa-plus"></i> New Tag</button> -->
            </div>
          </fieldset>
      </form>
    </div>
  </div>
</div>
<div id="tags" style="display:none;"></div>

{% endblock %}

{% block extra_js %}
<script src="https://cdn.metroui.org.ua/v4/js/metro.min.js"></script>
<script type="text/javascript" src="{% static 'js/tagsinput.js' %}"></script>
<script type="text/javascript">

function taginput() {
  $.ajax({
      url: "{% url 'user:get_all_tags' %}",
      dataType: "html",
      data: {"csrfmiddlewaretoken": "{{csrf_token}}"},
      type: "POST",
      success: function(result) {
          $("#blogTagsDiv").html(result);
      }
  });
}

$("#finishNewTagBtn").on("click", function(e) {
    e.preventDefault();

    var newTag = $("#newTagInputValue").val();
    if(newTag.length == 0) {
        $("#newTagErrorSpan").attr("class", "error-message")
        $("#newTagErrorSpan").text("Tag Cannot Be Empty.")
        $("#newTagErrorSpan").show();
        // $("#tagModal").modal("show");
    } else {
        $.ajax({
            url: "{% url 'user:add_new_tag' %}",
            dataType: "json",
            type: "POST",
            data: {"csrfmiddlewaretoken": "{{csrf_token}}", "new_tag": newTag},
            success: function(result) {
                if(result.status == "success") {
                    $("#newTagErrorSpan").attr("class", "success-message")
                    $("#newTagErrorSpan").text("Added new tag successfully");
                    $("#newTagErrorSpan").show();
                    for(i=0; i<result.tags.length; i++) {
                        $("#id_blog_tags").append("<option value='"+result["tags"][i][0]+"'>"+result["tags"][i][1]+"</option>");
                    }
                } else {
                    $("#newTagErrorSpan").attr("class", "error-message")
                    $("#newTagErrorSpan").text("Something went wrong");
                    $("#newTagErrorSpan").show();
                }
            }
        });
    }
});

$("#editPreviewBlog").on("click", function(event) {
  event.preventDefault();

  $("#editPostForm").attr("action", "url 'blog:preview_from_edit_blog'");
  $("#editPostForm #type").val("preview");
  $("#editPostForm").submit();

});

$("#previewAndSave").on("click", function(event) {
  event.preventDefault();

  $("#editPostForm").attr("action", "url 'blog:preview_from_edit_blog'");
  $("#editPostForm #type").val("preview");
  $("#editPostForm").submit();

});


// $("#draftBtn").on("click", function() {
//   event.preventDefault();
//
//   $("#newBlogForm").attr("action", "{% url 'blog:write_new_blog' %}");
//   $("#newBlogForm #type").val("draft");
//   $("#newBlogForm").submit();
// });

$("#submitForModerationEdit").on("click", function() {
  event.preventDefault();
  console.log("submitForModeration clicked");
  $("#editPostForm").attr("action", "{% url 'blog:write_new_blog' %}");
  $("#editPostForm #type").val("submitForModeration");
  $("#editPostForm").submit();
});
</script>
{% endblock %}