api/urls.py
from rest_framework.urlpatterns import format_suffix_patterns
from django.urls import path, re_path
from .views import PostList, PostDetail

app_name = "api"

urlpatterns = [
    path('', PostList.as_view(), name="api_bloglist"),
    path('post/<int:pk>/', PostDetail.as_view(), name="api_blogdetail"),
]

urlpatterns = format_suffix_patterns(urlpatterns)

blog/urls.py
from django.urls import path, re_path
from . import views

app_name = "blog"

urlpatterns = [
    path('search/', views.blog_search, name="blog_search"),
    path('categories/', views.get_categories, name="blog_categories"),
    path('my-blogs/', views.my_blogs, name="my_blogs"),
    path('new-blog-post/', views.write_new_blog, name="write_new_blog"),
    path('new-blog-post-preview/', views.save_blog_and_show_preview, name="save_blog_and_show_preview"),
    # path('blog/submit-for-moderation/', views.submit_blog_for_moderation, name="submit_blog_for_moderation"),
    path('blog-tags/', views.blog_tags, name="blog_tags"),
    re_path(r'^edit-blog-post/(?P<id>[\d]+)/(?P<slug>[\w\d-]+)/$', views.edit_blog, name="edit_blog_post"),
    #
    re_path(r'ajax/bookmark/(?P<id>[\d]+)$', views.bookmark_blogpost, name="bookmark_blogpost"),
    re_path(r'ajax/like/(?P<id>[\d]+)$', views.like_blogpost, name="like_blogpost"),
    re_path(r'ajax/blog-request/(?P<category_id>[\d]+)$', views.blog_request, name="blog_request"),
    re_path(r'^ajax/submit-for-moderation-preview/$', views.submit_for_moderation, name="submit_for_moderation"),
    #
    re_path(r'^(?P<id>[\d]+)/(?P<slug>[\w\d-]+)/$', views.blog_detail, name="blog_detail"),
    re_path(r'^draft/(?P<id>[\d]+)/(?P<slug>[\w\d-]+)/$', views.draft_blog_detail, name="draft_blog_detail"),
    re_path(r'^awaiting-moderation/(?P<id>[\d]+)/(?P<slug>[\w\d-]+)/$', views.awaiting_moderation_blog_detail, name="awaiting_moderation"),
    re_path(r'^preview/(?P<id>[\d]+)/(?P<blog_slug>[\w\d-]+)/$', views.preview_blog, name="preview_blog"),
    # re_path(r'^preview/from-edit-blog/$', views.preview_from_edit_blog, name="preview_from_edit_blog"),
    #
    re_path(r'^filter-by-category/(?P<category_slug>[\w\d-]+)$', views.filter_by_category, name="filter_by_category"),
    re_path(r'^filter-by-tag/(?P<slug>[\w\d-]+)$', views.filter_by_tag, name="filter_by_tag"),
    re_path(r'^filter-by-author/(?P<id>[\d]+)$', views.filter_by_author, name="filter_by_author"),
    #
    re_path(r'^accept-and-publish/blog/(?P<id>[\d]+)/$', views.accept_and_publish, name="accept_and_publish"),
]

user/urls.py
from django.urls import path, re_path
from . import views

app_name = "user"

urlpatterns = [
    path('', views.index, name="index"),
    path('about-us/', views.about, name="about_us"),
    re_path(r'^drafts/$', views.user_drafts, name="user_drafts"),
    re_path(r'^ajax/follow-author/$',  views.follow, name="follow_author"),
    path('interests/', views.user_interests, name="user_interests"),
    path('page-not-found', views.pagenotfound, name="pagenotfound"),
    path('dashboard/', views.user_dashboard, name="user_dashboard"),
    path('ajax/get-user-info/', views.get_user_information, name="get_user_information"),
    path('ajax/unfollow-author/', views.unfollow_author, name="unfollow_author"),
    path('ajax/get-all-tags/', views.get_all_tags, name="get_all_tags"),
    path('ajax/add-new-tag/', views.add_new_tag, name="add_new_tag"),
    path('ajax/mark-as-read/', views.mark_as_read, name="mark_as_read"),
    path('moderator-dashboard/', views.moderator_dashboard, name="moderator_dashboard"),
    path('notifications/', views.notifications, name="notifications")
]

user/models.py
from django.db import models
from django.contrib.auth.models import User
from blog.models import BlogPost


# Create your models here.
class Profile(models.Model):
    GENDER_CHOICES = (
        ('M', 'MALE'),
        ('F', 'FEMALE'),
        ('O', 'OTHER')
    )

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    date_of_birth = models.DateField(blank=True, null=True)
    gender = models.CharField(choices=GENDER_CHOICES, blank=True, null=True, max_length=1)
    roles = models.ForeignKey('blog.Role', on_delete=models.CASCADE, null=True, blank=True)
    interests = models.ManyToManyField('blog.Category')
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "profile"

    def __str__(self):
        return self.user.username


class PersonalInformation(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    introduction = models.CharField(max_length=200)
    full_introduction = models.TextField(default="")
    picture = models.ImageField()
    interests = models.ManyToManyField('blog.Category')

    # Social media only to authors.
    facebook = models.URLField(null=True, blank=True)
    github = models.URLField(null=True, blank=True)
    linkedin = models.URLField(null=True, blank=True)
    twitter = models.URLField(null=True, blank=True)
    insta = models.URLField(null=True, blank=True)

    class Meta:
        db_table = "personal_information"

    def __str__(self):
        return self.user.username


class UserLikes(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    blog = models.ForeignKey('blog.BlogPost', on_delete=models.CASCADE)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    status = models.BooleanField(default=False)

    class Meta:
        db_table = "user_likes"

    def __str__(self):
        return self.user


class UserFollowing(models.Model):
    """Stores User(Viewer's) Follower list"""
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    following = models.ForeignKey(User, on_delete=models.CASCADE, related_name="following")
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    status = models.BooleanField(default=False)

    class Meta:
        db_table = "user_following"

    def __str__(self):
        return self.user.username


class UserBookmarks(models.Model):
    """Stores User(Viewer's) Blog Bookmarks"""
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    blog_post = models.ForeignKey('blog.BlogPost', on_delete=models.CASCADE, default=1)

    class Meta:
        verbose_name = "UserBookmark"
        verbose_name_plural = "UserBookmarks"

    def __str__(self):
        return self.user


class Notifications(models.Model):
    """Stores User's Notifications"""
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    read = models.BooleanField(default=False)
    url = models.URLField(blank=True, null=True)
    # blog_post = models.ForeignKey(BlogPost, on_delete=models.CASCADE)
    notify = models.ForeignKey(User, on_delete=models.CASCADE, related_name="notify_author")
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Notification"
        verbose_name_plural = "Notifications"

    def __str__(self):
        return self.title

user/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import JsonResponse, HttpResponse
from .models import Profile, UserFollowing
from django.contrib.auth.models import User, Group
from toolbelt.utils import use_directory_path, banner_directory_path
from blog.models import BlogPost, Category
from user.models import UserLikes, UserBookmarks, UserFollowing, PersonalInformation, Notifications
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.utils.text import slugify
from django.db.models import Q

from datetime import datetime

def validate_author_exist_or_not(author_id):
    try:
        author_exists = Profile.objects.filter(id=author_id)
        if len(author_exists) > 0:
            return author_exists[0]
    except Exception as e:
        if e:
            return False


def index(request):
    blogs = BlogPost.objects.filter(
        published=True, moderator_accepted=True,
        preview=False, draft=False
        ).order_by("-created_on")
    query = request.GET.get('q')
    if query:
        blogs = BlogPost.objects.filter(
            published=True, moderator_accepted=True,
            preview=False, draft=False
        )

    paginator = Paginator(blogs, 6)  # 3 blogs per page.
    page = request.GET.get('page')
    try:
        blogs = paginator.page(page)
    except PageNotAnInteger:
        blogs = paginator.page(1)
    except EmptyPage:
        blogs = paginator.page(paginator.num_pages)

    return render(request, "index.html", context={'blogs': blogs})


def about(request):
    # authors = User.objects.filter(groups__name="author")
    authors = PersonalInformation.objects.filter(Q(user__groups__name="author") | Q(user__groups__name="moderator"))
    return render(request, "about.html", context={"authors": authors})


def follow(request):
    if request.is_ajax() and request.user.is_authenticated:
        author = validate_author_exist_or_not(request.POST.get('author_id'))
        author = User.objects.get(username=author)
        follows = False
        context = {}

        if author is not False:
            try:
                follow_check = UserFollowing.objects.filter(user=request.user, following=author)
                if len(follow_check) > 0:
                    if follow_check[0].status is True:
                        userfollowObj = follow_check[0]
                        userfollowObj.status = False
                        userfollowObj.save()
                        follows = userfollowObj.status
                        context["follow_obj"] = userfollowObj
                        context["follows"] = follows
                    else:
                        userfollowObj = follow_check[0]
                        userfollowObj.status = True
                        userfollowObj.save()

                        # Add to notification
                        notification = Notifications.objects.create(
                            user=request.user,
                            title="{} has followed you.".format(request.user.username),
                            notify=author
                            )
                        notification.save()

                        follows = userfollowObj.status
                        context["follow_obj"] = userfollowObj
                        context["follows"] = follows

                else:
                    userfollowObj = UserFollowing.objects.create(user=request.user, following=author, status=True)
                    userfollowObj.save()
                    # Add to notification
                    notification = Notifications.objects.create(
                        user=request.user,
                        title="{} has followed you.".format(request.user.username),
                        notify=author
                        )
                    notification.save()
                    
                    follows = userfollowObj.status
                    context["follow_obj"] = userfollowObj
                    context["follows"] = follows

            except Exception:
                pass
            return render(request, "user/ajax/components.html", context)
        else:
            pass
    else:
        return JsonResponse({"error": "Sorry something went wrong. Please try later.", "authenticated": False}, status=300)


@login_required
def user_interests(request):
    if request.method == "POST":
        categories = request.POST.getlist('rGroup')
        all_categories = [cat.category_slug for cat in list(Category.objects.all())]
        check = [True if cat in all_categories else False for cat in categories]

        if True in check:
            userProfile = Profile.objects.get(user=request.user)
            for interest in userProfile.interests.all():
                userProfile.interests.remove(interest)

            for cat in categories:
                userProfile.interests.add(Category.objects.get(category_slug=cat))
                # save_category.save()
            messages.success(request, "Your interests saved.")
            return redirect("user:user_interests")

        elif len(check) == 0:
            messages.error(request, "You should select at least one category.")

            return redirect("user:user_interests")
        else:
            return redirect("user:pagenotfound")
    else:
        categories = Category.objects.all()
        userProfile = Profile.objects.get(user=request.user)
        user_interests = userProfile.interests.all()
        return render(request, "user/interests.html", context={'categories': categories, 'user_interests': user_interests})


def pagenotfound(request):
    return render(request, "pagenotfound.html")


@login_required
def user_drafts(request):
    try:
        author_group = Group.objects.get(name='author')
        moderator_group = Group.objects.get(name='moderator')
    except Group.DoesNotExist:
        return redirect("user:pagenotfound")

    if request.user.groups.filter(name=author_group).exists() or request.user.groups.filter(name=moderator_group).exists():
        blogs = BlogPost.objects.filter(blog_author=request.user, preview=True, draft=True, published=False)
        return render(request, "user/user_drafts.html", context={"blogs": blogs})
    else:
        return redirect("user:pagenotfound")


@login_required
def get_all_tags(request):
    # if request.method == "POST" and request.is_ajax():
    #     tags_list = []
    #     for t in Tag.objects.all():
    #         tags_list.append(t.tag_name)
    #
    #     print(tags_list)
    #     return JsonResponse({"status": "success", "tags": ",".join(tags_list)}, status=200)
    # else:
    #     return JsonResponse({"status": "failure"}, status=404)
    pass


@login_required
def add_new_tag(request):
    pass
#     if request.method == "POST" and request.is_ajax():
#         tag_names = request.POST.get("new_tag")
#         print(tag_names)
#         if len(tag_names) > 0:
#             tag_names = tag_names.split(",")
#             tags_list = {}
#             for tag_name in tag_names:
#                 newtag = Tag.objects.create(
#                     tag_name=tag_name,
#                     tag_slug=slugify(tag_name)
#                 )
#                 newtag.save()
#                 tags_list[newtag.id] = [newtag.id, newtag.tag_name]
#
#             return JsonResponse({"status": "success", "tags": tags_list}, status=200)
#     else:
#         return JsonResponse({"status": "failure"}, status=400)


@login_required
def user_dashboard(request):
    # profile = Profile.objects.get(user=request.user)
    try:
        author_group = Group.objects.get(name='author')

        if request.user.groups.filter(name=author_group).exists():
            user_bookmarks = UserBookmarks.objects.filter(user=request.user)
            following = UserFollowing.objects.filter(user=request.user)
            users_following_you = UserFollowing.objects.filter(following=request.user)
            user_likes = UserLikes.objects.filter(user=request.user, status=True)
            my_blogs_count = BlogPost.objects.filter(blog_author=request.user).count()
            my_blogs_unpublished_count = BlogPost.objects.filter(blog_author=request.user, published=False, draft=True, preview=True).count()
            my_blogs_published_count = BlogPost.objects.filter(blog_author=request.user, published=True, moderator_accepted=True).count()
            my_blogs_moderation_count = BlogPost.objects.filter(blog_author=request.user, moderator_accepted=False, submitted_for_moderation=True).count()

            return render(request, "user/author_dashboard.html", context={
                "user_likes": user_likes,
                "user_bookmarks": user_bookmarks,
                "following": following,
                "users_following_you": users_following_you,
                "my_blogs_count": my_blogs_count,
                "my_blogs_unpublished_count": my_blogs_unpublished_count,
                "my_blogs_published_count": my_blogs_published_count,
                "my_blogs_moderation_count": my_blogs_moderation_count
                })

    except Group.DoesNotExist:
        return redirect("user:pagenotfound")

    try:
        moderator_group = Group.objects.get(name='moderator')
        if request.user.groups.filter(name=moderator_group).exists():
            return redirect("user:moderator_dashboard")
    except Group.DoesNotExist:
        return redirect("user:pagenotfound")

    user_bookmarks = UserBookmarks.objects.filter(user=request.user)
    following = UserFollowing.objects.filter(user=request.user)
    user_likes = UserLikes.objects.filter(user=request.user)

    return render(request, "user/dashboard.html", context={
        "user_likes": user_likes,
        "user_bookmarks": user_bookmarks,
        "following": following
        })


@login_required

user/templates/user/interests.html
{% extends "base.html" %}
{% load static %}

{% block title %} Interests {% endblock %}

{% block content %}
  <div class="container oc-screen interests-div">
    <h1 class="text-center blog-category-page-heading">Select the Categories you are interested in.</h1>
    <p class="text-center">This will help us to suggest articles that you are interested in. You can undo this whenever you want.</p>

    {% if messages %}
      <div class="row">
        <div class="col-md-6 mx-auto">
          {% for msg in messages %}
          <div class="alert alert-{{msg.level_tag}} custom-messages" role="alert">
              {{msg.message}}
          </div>
          {% endfor %}
        </div>
      </div>
    {% endif %}

    <div class="row" id="checkboxes">
      <form class="col-md-8 mx-auto form-inline interests-form" action="{% url 'user:user_interests' %}" method="post">
        {% csrf_token %}
        {% for category in categories %}
        <div class="col-md-3 col-sm-6 col-6 form-group interests-item">
          <label class="label">
            <input type="checkbox" name="rGroup" value="{{category.category_slug}}" id="{{category.id}}" {% if category in user_interests %}checked="checked"{% endif %}/>
            <label class="whatever" for="{{category.id}}">{{category.category_name}}</label>
          </label>
        </div>
        {% endfor %}

        <div class="col-md-12 interestsFormSaveDiv mt-2">
          <div class="col-md-3 form-group mx-auto">
            <input type="submit" name="saveCategory" value="Save" class="btn btn-primary btn-block">
          </div>
        </div>
      </form>
    </div>
  </div>
{% endblock %}

user/templates/user/notifications.html
{% extends "base.html" %}
{% load static customtags crispy_forms_tags %}

{% block title %} User Notifications {% endblock %}

{% block extra_head %}
<link rel="stylesheet" href="{% static 'css/toast.min.css' %}">
{% endblock %}

{% block home_banner %} {% endblock %}

{% block content %}
  <div class="container oc-screen interests-div">
    <h1 class="text-center blog-category-page-heading">Notifications.</h1>
    <p class="text-center">You'll see all your notifications here.</p>

    {% if messages %}
      <div class="row">
        <div class="col-md-6 mx-auto">
          {% for msg in messages %}
          <div class="alert alert-{{msg.level_tag}} custom-messages" role="alert">
              {{msg.message}}
          </div>
          {% endfor %}
        </div>
      </div>
    {% endif %}

    <div class="row" id="checkboxes">
      {% if unread_notifications %}
      	{% for notification in unread_notifications %}
			<div class="col-md-10 mx-auto unread-notification-div" id="unread{{notification.id}}">
		      <a href="{{notification.url}}" class="float-left">
					<p class="unread-notification-title">
						{{notification.title}}
					</p>
		      </a>
		      <div class="float-right" id="markasread{{notification.id}}">
				<a href="#!" class="mark-as-read" id="{{notification.id}}">
					<i class="fa fa-check-circle-o"></i><small> Mark As Read</small>
				</a>
				{{notification.created_on|date:"M d, Y"}}
		      </div>
			</div>
      	{% endfor %}
      {% endif %}

      {% if read_notifications %}
		{% for notification in read_notifications %}
		<div class="col-md-10 mx-auto read-notification-div" id="read{{notification.id}}">
		  <a href="{{notification.url}}" class="float-left">
			<p class="read-notification-title">{{notification.title}}</p>
		  </a>
		  <div class="float-right">
			<p class="pt-1 mb-0">
				{{notification.created_on|date:"M d, Y"}}
			</p>
		  </div>
		</div>
		{% endfor %}
	{% endif %}
    </div>
  </div>
{% endblock %}


{% block extra_js %}
<script type="text/javascript">
	$(".mark-as-read").on("click", function() {
		nId = this.id;
		$.ajax({
			url: "{% url 'user:mark_as_read' %}",
			data: {"csrfmiddlewaretoken": "{{csrf_token}}", "notification_id": nId},
			type: "POST",
			dataType: "json",
			success: function(result) {
				if(result) {
					$(".mark-as-read#"+nId).hide();
					$("#unread"+nId).removeClass("unread-notification-div").addClass("read-notification-div");
				}
			}
		});
	});
</script>
{% endblock %}

user/templates/user/user_drafts.html
{% extends "base.html" %}
{% load static %}
{% block title %} User Drafts {% endblock %}

{% block content %}
<div class="container-fluid allblogs-div">
  <div class="container oc-screen">
      {% if messages %}
        <div class="row">
          <div class="col-md-6 mx-auto">
            {% for msg in messages %}
            <div class="alert alert-{{msg.level_tag}} custom-messages" role="alert">
                {{msg.message}}
            </div>
            {% endfor %}
          </div>
        </div>
      {% endif %}
      <div class="">
        <div class="row blog-main-heading-outer-div">
            <div class="blog-main-heading-inner-div" style="width: 20%;">
                <h3 class="text-center">Your Drafts</h3>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                {% if blogs %}
                <div class="row equal">
                  {% for blog in blogs %}
                  <div class="col-md-4 col-sm-4 col-12">
                    <div class="card card-div">
                      <!-- <img class="card-img-top" src="{% static 'img/banner.jpg' %}" alt="Card image cap"> -->
                        <a href="{% url 'blog:draft_blog_detail' id=blog.id slug=blog.blog_slug %}">
                            <div class="outer-div">
                                <div class="layer">{{blog.blog_title}}</div>
                                <div class="inner-div" style='background-image: url("{{blog.banner_image.url}}");'>

                                </div>
                            </div>
                        </a>
                        <div class="card-body">
                            <div class="blog-intro">
                              <span></span>
                              <small>By: <a href="#">{{blog.blog_author.user.username|upper}}</a> &nbsp; On: <b>{{blog.created_on|date:"M d, Y"}}</b> </small><br><br>
                              <p>{{blog.blog_subtitle|truncatechars:30}}<a href="{% url 'blog:draft_blog_detail' id=blog.id slug=blog.blog_slug %}" class="text-primary"> <b>Read Blog</b>
                              </a></p>
                              <p><span class="badge badge-light blog-badge">{{blog.blog_category}}</span></p>
                            </div>
                        </div>
                      </div>
                  </div>
                  {% endfor %}
                </div>
                {% else %}
                <div class="col-md-8 mx-auto">
                    <h3 class="text-center">You have no drafts.</h3>
                </div>
                {% endif %}
            </div> <!-- End of left side blogs list container -->
        </div>
      </div>

  </div>
</div>
{% endblock %}