api/urls.py
from rest_framework.urlpatterns import format_suffix_patterns
from django.urls import path, re_path
from .views import PostList, PostDetail

app_name = "api"

urlpatterns = [
    path('', PostList.as_view(), name="api_bloglist"),
    path('post/<int:pk>/', PostDetail.as_view(), name="api_blogdetail"),
]

urlpatterns = format_suffix_patterns(urlpatterns)

blog/urls.py
from django.urls import path, re_path
from . import views

app_name = "blog"

urlpatterns = [
    path('search/', views.blog_search, name="blog_search"),
    path('categories/', views.get_categories, name="blog_categories"),
    path('my-blogs/', views.my_blogs, name="my_blogs"),
    path('new-blog-post/', views.write_new_blog, name="write_new_blog"),
    path('new-blog-post-preview/', views.save_blog_and_show_preview, name="save_blog_and_show_preview"),
    # path('blog/submit-for-moderation/', views.submit_blog_for_moderation, name="submit_blog_for_moderation"),
    path('blog-tags/', views.blog_tags, name="blog_tags"),
    re_path(r'^edit-blog-post/(?P<id>[\d]+)/(?P<slug>[\w\d-]+)/$', views.edit_blog, name="edit_blog_post"),
    #
    re_path(r'ajax/bookmark/(?P<id>[\d]+)$', views.bookmark_blogpost, name="bookmark_blogpost"),
    re_path(r'ajax/like/(?P<id>[\d]+)$', views.like_blogpost, name="like_blogpost"),
    re_path(r'ajax/blog-request/(?P<category_id>[\d]+)$', views.blog_request, name="blog_request"),
    re_path(r'^ajax/submit-for-moderation-preview/$', views.submit_for_moderation, name="submit_for_moderation"),
    #
    re_path(r'^(?P<id>[\d]+)/(?P<slug>[\w\d-]+)/$', views.blog_detail, name="blog_detail"),
    re_path(r'^draft/(?P<id>[\d]+)/(?P<slug>[\w\d-]+)/$', views.draft_blog_detail, name="draft_blog_detail"),
    re_path(r'^awaiting-moderation/(?P<id>[\d]+)/(?P<slug>[\w\d-]+)/$', views.awaiting_moderation_blog_detail, name="awaiting_moderation"),
    re_path(r'^preview/(?P<id>[\d]+)/(?P<blog_slug>[\w\d-]+)/$', views.preview_blog, name="preview_blog"),
    # re_path(r'^preview/from-edit-blog/$', views.preview_from_edit_blog, name="preview_from_edit_blog"),
    #
    re_path(r'^filter-by-category/(?P<category_slug>[\w\d-]+)$', views.filter_by_category, name="filter_by_category"),
    re_path(r'^filter-by-tag/(?P<slug>[\w\d-]+)$', views.filter_by_tag, name="filter_by_tag"),
    re_path(r'^filter-by-author/(?P<id>[\d]+)$', views.filter_by_author, name="filter_by_author"),
    #
    re_path(r'^accept-and-publish/blog/(?P<id>[\d]+)/$', views.accept_and_publish, name="accept_and_publish"),
]

user/urls.py
from django.urls import path, re_path
from . import views

app_name = "user"

urlpatterns = [
    path('', views.index, name="index"),
    path('about-us/', views.about, name="about_us"),
    re_path(r'^drafts/$', views.user_drafts, name="user_drafts"),
    re_path(r'^ajax/follow-author/$',  views.follow, name="follow_author"),
    path('interests/', views.user_interests, name="user_interests"),
    path('page-not-found', views.pagenotfound, name="pagenotfound"),
    path('dashboard/', views.user_dashboard, name="user_dashboard"),
    path('ajax/get-user-info/', views.get_user_information, name="get_user_information"),
    path('ajax/unfollow-author/', views.unfollow_author, name="unfollow_author"),
    path('ajax/get-all-tags/', views.get_all_tags, name="get_all_tags"),
    path('ajax/add-new-tag/', views.add_new_tag, name="add_new_tag"),
    path('ajax/mark-as-read/', views.mark_as_read, name="mark_as_read"),
    path('moderator-dashboard/', views.moderator_dashboard, name="moderator_dashboard"),
    path('notifications/', views.notifications, name="notifications")
]

templates/snippets/footer.html
{% load static customtags %}
<footer class="page-footer font-small blue pt-4">
    <!-- Footer Links -->
    <div class="container-fluid text-center text-md-left">
    <!-- Grid row -->
    <div class="row">
      <!-- Grid column -->
      <div class="col-md-3 mt-md-0 mt-3">
        <!-- Content -->
        <h5 class="text-uppercase">Thetechbrainer</h5>
        <p>Place Where You Find Techblogs On New Topics Every Week.</p>
      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none pb-3">

      <!-- Grid column -->
      <div class="col-md-3 mb-md-0 mb-3">

        <!-- Links -->
        <h5 class="text-uppercase">Sitemap</h5>

        <ul class="list-unstyled">
          <li>
            <a href="{% url 'user:about_us' %}">About Us</a>
          </li>
          <li>
            <a href="{% url 'blog:blog_categories' %}">Blog Categories</a>
          </li>

          {% if request.user.is_authenticated %}
          {% if request.user|has_group:"moderator" %}
          <li>
              <a href="{% url 'user:moderator_dashboard' %}">Dashboard</a>
          </li>
          {% else %}
          <li>
              <a href="{% url 'user:user_dashboard' %}">Dashboard</a>
          </li>
          {% endif %}
          {% endif %}
          {% if request.user|has_group:"author" or request.user|has_group:"moderator" %}
          <li>
              <a href="{% url 'user:user_drafts' %}"> My Drafts</a>
          </li>
          {% endif %}
        </ul>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-3 mb-md-0 mb-3">

        <!-- Links -->
        <h5 class="text-uppercase">Contact Us</h5>

        <ul class="list-unstyled">
          <li>
            Email: <a href="mailto:thetechbrainer@gmail.com">thetechbrainer@gmail.com</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-3 mb-md-0 mb-3">
        <!-- Links -->
        <h5 class="text-uppercase">Follow Us On</h5>

        <ul class="list-unstyled list-inline">
          <li class="list-inline-item">
            <a href="https://www.facebook.com/thetechbrainer"><img src="{% static 'img/facebook.png' %}" width="50" height="50"/></a>
          </li>
          <li class="list-inline-item">
            <a href="https://instagram.com/thetechbrainer"><img src="{% static 'img/instagram.png' %}" width="50" height="50"/></a>
          </li>
          <li class="list-inline-item">
            <a href="#!"><img src="{% static 'img/twitter.png' %}" width="50" height="50"/></a>
          </li>
        </ul>
      </div>
      <!-- Grid column -->
    </div>
    <!-- Grid row -->
    </div>
    <!-- Footer Links -->
    <div class="text-center py-3">
      Made With <i class="fa fa-heart" aria-hidden="true" style="color:red"></i> &amp; <i class="fa fa-coffee" aria-hidden="true"></i>
    </div>
    <div class="footer-copyright text-center py-3">
      Copyright © {{year}}
        <a href="https://thetechbrainer.com/"> thetechbrainer.com</a>
    </div>
</footer>

templates/snippets/nav.html
{% load static customtags %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
<div class="container">
  <a class="navbar-brand" href="{% url 'user:index' %}"><b>Thetechbrainer</b></a>
  <i class="fa fa-search" data-toggle="modal" data-target="#blogSearchModal" aria-hidden="true" style="font-size: 20px; color: #fff; cursor:pointer;" id="navbarSearchIcon"></i>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
      {% if author_waiting_for_publish and request.user|has_group:"moderator" %}
      <i class="moderator-notification-nav-button" data-toggle="tooltip" data-placement="bottom" title="{% if author_waiting_for_publish %}New Notification{% endif %}"></i>
      {% endif %}
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarColor02">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'user:index' %}">Home</a>
        </li>
        <li class="nav-item">
        <a class="nav-link" href="{% url 'blog:blog_categories' %}">Categories</a>
        </li>
        <li class="nav-item">
        <a class="nav-link" href="{% url 'user:about_us' %}">About</a>
        </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
        <!-- Dropdown -->
        {% if request.user.is_authenticated %}
          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">

              {% if author_waiting_for_publish and request.user|has_group:"moderator" %}
              <i class="moderator-notification" data-toggle="tooltip" data-placement="bottom" title="{% if author_waiting_for_publish %}New Notification{% endif %}"></i>
              {% endif %}

              {% if unread_notifications %}
              <i class="blog-notification" data-toggle="tooltip" data-placement="bottom" title="{% if new_notifications %}New Notification{% endif %}"></i>
              {% endif %}

            {{request.user.username|title}}
          </a>
          <div class="dropdown-menu">
              {% if request.user.is_authenticated %}
                {% if all_notifications %}
                <a class="dropdown-item new_notifications" href="{% url 'user:notifications' %}">
                  
                  <i class="fa fa-bell"></i>&nbsp;View Notifications
                  {% if unread_notifications %}
                  <i class="blog-notification" data-toggle="tooltip" data-placement="bottom" title="{% if new_notifications %}New Notification{% endif %}"></i>
                  {% endif %}

                </a>
                {% endif %}

                {% if request.user|has_group:"moderator" %}
                <a class="dropdown-item" href="{% url 'user:moderator_dashboard' %}">
                    <i class="fa fa-line-chart" aria-hidden="true"></i>&nbsp;Dashboard
                    {% if author_waiting_for_publish and request.user|has_group:"moderator" %}
                    <i class="moderator-notification" data-toggle="tooltip" data-placement="bottom" title="{% if author_waiting_for_publish %}New Notification{% endif %}"></i>
                    {% endif %}
                </a>
                {% else %}
                <a class="dropdown-item" href="{% url 'user:user_dashboard' %}"> <i class="fa fa-tachometer"></i>&nbsp;Dashboard</a>
                {% endif %}
                {% if request.user|has_group:"author" or request.user|has_group:"moderator" %}
                <a class="dropdown-item" href="{% url 'user:user_drafts' %}"><i class="fa fa-file" aria-hidden="true"></i>&nbsp;My Drafts</a>
                {% endif %}

                {% if request.user|has_group:"author" or request.user|has_group:"moderator" %}
                <a class="dropdown-item" href="{% url 'blog:write_new_blog' %}"><i class="fa fa-plus" aria-hidden="true"></i> New Blog</a>
                {% endif %}

              <!-- <a class="dropdown-item" href="#"><i class="fa fa-user"></i>&nbsp;&nbsp;My Profile</a> -->
              <!-- <a class="dropdown-item" href="#"><i class="fa fa-gear"></i> Settings</a> -->
              {% if request.user|has_group:"author" or request.user|has_group:"moderator" %}
              <a class="dropdown-item" href="{% url 'blog:my_blogs' %}"><i class="fa fa-list-alt" aria-hidden="true"></i>&nbsp;&nbsp;My Blogs</a>
              {% endif %}
              <a class="dropdown-item" href="{% url 'account_change_password' %}"><i class="fa fa-key"></i>&nbsp;&nbsp;Change password</a>
              <a class="dropdown-item" href="{% url 'user:user_interests' %}"><i class="fa fa-bolt" aria-hidden="true"></i>&nbsp;&nbsp;Interests</a>
              <a class="dropdown-item" href="{% url 'account_logout' %}"><i class="fa fa-sign-out"></i>&nbsp;&nbsp;Logout</a>
              {% endif %}
          </div>
        </li>
        {% else %}
        <li class="nav-item"> <a class="nav-link" href="{% url 'account_login' %}">Login</a> </li>
        <li class="nav-item"> <a class="nav-link" href="{% url 'account_signup' %}">Signup</a> </li>
        {% endif %}
    </ul>
    <form class="form-inline my-2 my-lg-0 navsearchform" action="{% url 'blog:blog_search' %}" method="post">
      {% csrf_token %}
      <input class="form-control mr-sm-2 blogSearch" type="text" placeholder="Search Blog" name="blogsearch" required />
      <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</div>
</nav>

templates/snippets/sidebox.html
<!-- Right side box -->
<div class="col-md-4">
    <div class="panel panel-info side-box-panelinfo related-posts-sidebox">
      <div class="panel-heading">
          <h3 class="panel-title">
              <span class="glyphicon glyphicon-list-alt"></span>  Recent Posts
          </h3>
      </div>
      <hr />
      <div class="panel-body">
          <ul class="media-list">
              {% for post in recent_posts %}
              <li class="media">
                  <div class="media-body">
                      <h4 class="media-heading">
                          <a href="{% url 'blog:blog_detail' id=post.id slug=post.blog_slug %}" class="text-primary">
                              {{post.blog_title}}
                          </a>
                      </h4>
                      <p class="margin-top-10 margin-bottom-20">
                          {{post.blog_subtitle}}
                      </p>
                  </div>
              </li>
              {% endfor %}
          </ul>
          <!-- <a href="#" class="btn btn-default btn-block">More Blog Posts »</a> -->
      </div>
    </div>
    <!-- End fluid width widget -->


    <!-- <div class="panel panel-info side-box-panelinfo">
      <div class="panel-heading">
          <h3 class="panel-title">
              <span class="glyphicon glyphicon-list-alt"></span>  Hash Tags
          </h3>
      </div>
      <hr />
      <div class="panel-body">
          <ul class="media-list">
              <li class="media">
                  <div class="media-body">
                      <p>
                      {% for tag in tags %}
                        <a href="{% url 'blog:filter_by_tag' slug=tag.slug %}">
                          <span class="badge badge-dark blog-badge">{{tag.tag_name}}</span>
                        </a>
                      {% endfor %}
                      </p>
                  </div>
              </li>
          </ul>
      </div>
    </div> -->
    <!-- End fluid width widget -->
</div> <!-- Right side box end -->