api/urls.py
from rest_framework.urlpatterns import format_suffix_patterns
from django.urls import path, re_path
from .views import PostList, PostDetail

app_name = "api"

urlpatterns = [
    path('', PostList.as_view(), name="api_bloglist"),
    path('post/<int:pk>/', PostDetail.as_view(), name="api_blogdetail"),
]

urlpatterns = format_suffix_patterns(urlpatterns)

blog/urls.py
from django.urls import path, re_path
from . import views

app_name = "blog"

urlpatterns = [
    path('search/', views.blog_search, name="blog_search"),
    path('categories/', views.get_categories, name="blog_categories"),
    path('my-blogs/', views.my_blogs, name="my_blogs"),
    path('new-blog-post/', views.write_new_blog, name="write_new_blog"),
    path('new-blog-post-preview/', views.save_blog_and_show_preview, name="save_blog_and_show_preview"),
    # path('blog/submit-for-moderation/', views.submit_blog_for_moderation, name="submit_blog_for_moderation"),
    path('blog-tags/', views.blog_tags, name="blog_tags"),
    re_path(r'^edit-blog-post/(?P<id>[\d]+)/(?P<slug>[\w\d-]+)/$', views.edit_blog, name="edit_blog_post"),
    #
    re_path(r'ajax/bookmark/(?P<id>[\d]+)$', views.bookmark_blogpost, name="bookmark_blogpost"),
    re_path(r'ajax/like/(?P<id>[\d]+)$', views.like_blogpost, name="like_blogpost"),
    re_path(r'ajax/blog-request/(?P<category_id>[\d]+)$', views.blog_request, name="blog_request"),
    re_path(r'^ajax/submit-for-moderation-preview/$', views.submit_for_moderation, name="submit_for_moderation"),
    #
    re_path(r'^(?P<id>[\d]+)/(?P<slug>[\w\d-]+)/$', views.blog_detail, name="blog_detail"),
    re_path(r'^draft/(?P<id>[\d]+)/(?P<slug>[\w\d-]+)/$', views.draft_blog_detail, name="draft_blog_detail"),
    re_path(r'^awaiting-moderation/(?P<id>[\d]+)/(?P<slug>[\w\d-]+)/$', views.awaiting_moderation_blog_detail, name="awaiting_moderation"),
    re_path(r'^preview/(?P<id>[\d]+)/(?P<blog_slug>[\w\d-]+)/$', views.preview_blog, name="preview_blog"),
    # re_path(r'^preview/from-edit-blog/$', views.preview_from_edit_blog, name="preview_from_edit_blog"),
    #
    re_path(r'^filter-by-category/(?P<category_slug>[\w\d-]+)$', views.filter_by_category, name="filter_by_category"),
    re_path(r'^filter-by-tag/(?P<slug>[\w\d-]+)$', views.filter_by_tag, name="filter_by_tag"),
    re_path(r'^filter-by-author/(?P<id>[\d]+)$', views.filter_by_author, name="filter_by_author"),
    #
    re_path(r'^accept-and-publish/blog/(?P<id>[\d]+)/$', views.accept_and_publish, name="accept_and_publish"),
]

templates/about.html
{% extends "base.html" %}
{% load static customtags crispy_forms_tags %}

{% block title %} About {% endblock %}

{% block home_banner %} {% endblock %}
{% block content %}
<div class="container-fluid author-dashboard-div" style="padding: 0px;">
    <div class="container">
        <div class="row aboutUsContainer">
            <div class="col-md-12 aboutUsHeading">
                <h1 class="text-center"> About Thetechbrainer</h1>
            </div>

            <div class="col-md-4 col-sm-12 col-12" style="width: 100%;">
                <div class="text-center" style="width: 50%; margin: 0 auto;">
                    <img src="{% static 'img/aboutus/sashikanth.jpg' %}" class="img-responsive" height="200" width="185" style="border-radius: 0%;"/>
                </div>
            </div>

            <div class="col-md-8 col-sm-12 col-12">
                <p class="aboutUsInfo">
                    Hello World, my name is <span class="text-primary">SASHIKANTH</span>, created Thetechbrainer.com to showcase my passion towards learning new technologies, &amp; most importantly share the knowledge with others.
                    <br><br><br>

                    With everyday passing, I learnt importance of technology, networking &amp; contributions to the OpenSource projects.
                    With plenty of things to learn in today's world, I would like to keep track of what I learned &amp; share with people who are interested to know more about technology topics.

                    <br><br><br>

                    So, We've decided to write one blog per week on specific topic and publish so that interested people can learn new things. If you have any specific topic you want us to cover in our blogs, feel free to contact us at <a href="mailto:thetechbrainer@gmail.com">thetechbrainer@gmail.com</a>

                </p>
            </div>
        </div>
    </div>

    <div class="aboutUsBanner" style="background-image: linear-gradient(to right, rgba(70, 197, 197, 0.52), rgba(128, 143, 200, 0.73)),
    url('{% static 'img/banner-laptop.jpg' %}');">

    </div>
    <br> <br>

    <div class="container">
        {% if authors %}
        <div class="row aboutUsHeading">
            <div class="col-md-12">
                <h1 class="text-center"> Our Authors</h1>
            </div>
        </div>
        <div class="row">
            {% for author in authors %}
            <div class="col-md-4 col-sm-6 col-12 card-deck">
                <div class="card card-div">
                    <img class="card-img-top" src="{% if author.picture %}{{author.picture.url}}{% else %}{% static 'img/default_avatar.jpg' %}{% endif %}" alt="{{author.siteuser.user}}">
                    <div class="card-body">
                    <h4 class="card-title text-center">{{author.user|title}}</h4>
                    <p class="card-text">{{author.introduction}}</p>
                    <div class="social-icons text-center">
                        {% if author.facebook %}
                        <a href="{{author.facebook}}" target="_blank">
                            <i class="fa fa-facebook-official" aria-hidden="true"></i>
                        </a>
                        {% endif %}
                        {% if author.twitter %}
                        <a href="{{author.twitter}}"  target="_blank">
                            <i class="fa fa-twitter-square" aria-hidden="true"></i>
                        </a>
                        {% endif %}

                        {% if author.linkedin %}
                        <a href="{{author.linkedin}}"  target="_blank">
                            <i class="fa fa-linkedin-square" aria-hidden="true"></i>
                        </a>
                        {% endif %}

                        {% if author.github %}
                        <a href="{{author.github}}"  target="_blank">
                            <i class="fa fa-github" aria-hidden="true"></i>
                        </a>
                        {% endif %}
                    </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        {% endif %}

        <div class="row aboutUsAuthors" style="background-color: #808FC8; background-image: linear-gradient(to right, #46c5c5 , #808FC8); color: #fff; font-family:Helvetica;">
            <div class="col-md-12">
                <p class="text-center">
                    We cover the wide range of topics like Software Development, Software Testing and much more as we learn and share with you. If you find certain category that has no blogs and you want one, just let us know by clicking "Let Author Know".
                </p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/auth_base.html
{% load static %}

<!DOCTYPE html>
<html class="no-js" lang="en">
    <head>
        <link rel="icon" href="{% static 'img/favicon.ico' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"> -->

        <link href="https://fonts.googleapis.com/css2?family=Chelsea+Market&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Chelsea+Market&family=Yanone+Kaffeesatz&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Abril+Fatface&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Arbutus+Slab&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@700&display=swap" rel="stylesheet">
        <!-- Font awesome -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-7HZT37TDCJ"></script>
        <script>
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());

          gtag('config', 'G-7HZT37TDCJ');
        </script>

        <title>
            {% block title %}{% endblock %} | Thetechbrainer
        </title>
        <meta charset="utf-8">
        <meta name="description" content="Thetechbrainer is a place where you find good tech blogs and tutorials. Our aim is to provide new tech blogs every week. We love to learn, understand and share the knowledge with the techbrainers out there. You can find blogs related to different categories of technology. If you are interested to bookmark or follow the authors you love, you can login and do it right away. Are you also interested to be part of thetechbrainers and want to contribute? leave us an email about you and your interests. Thetechbrainer will reach out to you and you can get access to be our beloved author." />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        {% block og_info %}
        {% endblock %}

        {% block extra_head %}

        {% endblock %}

        {# Global stylesheets #}
        <link rel="stylesheet" type="text/css" href="{% static 'css/thetechbrainer.css' %}">
        <style>
            .asteriskField {
                color: #ff0000;
            }
        </style>

        {% block extra_css %}
            {# Override this in templates to add extra stylesheets #}
        {% endblock %}
    </head>

    <body class="{% block body_class %}{% endblock %}">
        {% include "snippets/nav.html" %}
	    <div class="modal fade" id="blogSearchModal" role="dialog">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title">Search Blogs</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <form class="blog-search" action="{% url 'blog:blog_search' %}" method="post">
                  {% csrf_token %}
                  <label for="blogSearch"></label>
                  <input type="text" name="blogsearch" class="form-control blogSearch" value="" placeholder="Enter Blog name or Keywords" required /><br>
                  <button type="submit" name="search" class="btn btn-primary btn-md">Search</button>
                </form>
              </div>
            </div>
          </div>
        </div>

        {% block content %}{% endblock %}

        {# Global javascript #}
        <!-- Scripts Order matters. Jquery, Bootstrap, next custom scripts -->
        <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/thetechbrainer.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/notify.min.js' %}"></script>
        <script type="text/javascript">
          $(document).ready(function() {
            // success alerts. fadeaway.
            if($(".alert alert-success")) {
              $(".alert-success").fadeTo(2000, 500).slideUp(500, function(){
                $(".alert-success").slideUp(500);
              });
            } else {
              //
            }
          });
        </script>
        {% block extra_js %}

        {% endblock %}

        {% include "snippets/footer.html" %}
    </body>
</html>

templates/base.html
{% load static %}

<!DOCTYPE html>
<html class="no-js" lang="en">
    <head>
        <link rel="icon" href="{% static 'img/favicon.ico' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"> -->

        <link href="https://fonts.googleapis.com/css2?family=Chelsea+Market&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Chelsea+Market&family=Yanone+Kaffeesatz&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Abril+Fatface&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Arbutus+Slab&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@700&display=swap" rel="stylesheet">
        <!-- Font awesome -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <!-- Data Tables -->
        <link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css">

        <!-- Google Adsense -->
        <script data-ad-client="ca-pub-6486759556400726" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-7HZT37TDCJ"></script>
        <script>
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());

          gtag('config', 'G-7HZT37TDCJ');
        </script>

        <title>
            {% block title %}{% endblock %} | Thetechbrainer
        </title>
        <meta charset="utf-8" />
        <meta name="description" content="Thetechbrainer is a place where you find good tech blogs and tutorials. Our aim is to provide new tech blogs every week. We love to learn, understand and share the knowledge with the techbrainers out there. You can find blogs related to different categories of technology. If you are interested to bookmark or follow the authors you love, you can login and do it right away. Are you also interested to be part of thetechbrainers and want to contribute? leave us an email about you and your interests. Thetechbrainer will reach out to you and you can get access to be our beloved author." />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
        {% block og_info %}
        {% endblock %}

        {% block extra_head %}

        {% endblock %}

        {# Global stylesheets #}
        <link rel="stylesheet" type="text/css" href="{% static 'css/thetechbrainer.css' %}">
        <style type="text/css">
            .bootstrap-tagsinput {
                display: block !important;
            }
        </style>

        {% block extra_css %}
            {# Override this in templates to add extra stylesheets #}
        {% endblock %}
    </head>

    <body class="{% block body_class %}{% endblock %}">
        {% include "snippets/nav.html" %}

        <div class="modal fade" id="blogSearchModal" role="dialog">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title">Search Blogs</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
		  <form class="blog-search" action="{% url 'blog:blog_search' %}" method="post">
                  {% csrf_token %}
                  <label for="blogSearch"></label>
                  <input type="text" name="blogsearch" class="form-control blogSearch" value="" placeholder="Enter Blog name or Keywords" required /><br>
                  <button type="submit" name="search" class="btn btn-primary btn-md">Search</button>
                </form>
              </div>
            </div>
          </div>
        </div>

        {% if not request.user.is_authenticated %}
        <div class="container-fluid">
          {% block home_banner %}
          <div class="row banner-div">
            <div class="col-md-6 col-sm-4">
              <img src="{% static 'img/banner.jpg' %}" alt="coffee-man" class="float-right" height="400px" style="padding: 2px 0px;">
            </div>
            <div class="col-md-6 col-sm-8">
              <h1 class="text-center">
                  Tech<span
                     class="txt-rotate"
                     data-period="2000"
                     data-rotate='[ "nology", "Knowledg-E" ]'></span><br>&lt;/Dose&gt;
              </h1>
            </div>
          </div>
          {% endblock %}
        </div>
        {% endif %}


        {% block content %}{% endblock %}

        {# Global javascript #}
        <!-- Scripts Order matters. Jquery, Bootstrap, next custom scripts -->
        <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/thetechbrainer.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/notify.min.js' %}"></script>
        <script type="text/javascript" src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
        <script type="text/javascript">
          $(document).ready(function() {
            // success alerts. fadeaway.
            if($(".alert alert-success")) {
              $(".alert-success").fadeTo(2000, 500).slideUp(500, function(){
                $(".alert-success").slideUp(500);
              });
            } else {
              //
            }

            $.toastDefaults = {
              // top-left, top-right, bottom-left, bottom-right, top-center, and bottom-center
              position: 'bottom-left',

              // is dismissable?
              dismissible: true,

              // is stackable?
              stackable: true,

              // pause dely on hover
              pauseDelayOnHover: true,

              // additional CSS Classes
              style: {
                toast: '',
                info: '',
                success: '',
                warning: '',
                error: '',
              }

            };
          });

        </script>
        {% block extra_js %}

        {% endblock %}

        {% include "snippets/footer.html" %}
        <div id="stop" class="scrollTop">
            <span><a href="#">Top</a></span>
        </div>
        <script type="text/javascript">
            var TxtRotate = function(el, toRotate, period) {
                this.toRotate = toRotate;
                this.el = el;
                this.loopNum = 0;
                this.period = parseInt(period, 10) || 2000;
                this.txt = '';
                this.tick();
                this.isDeleting = false;
            };

            TxtRotate.prototype.tick = function() {
                var i = this.loopNum % this.toRotate.length;
                var fullTxt = this.toRotate[i];

                if (this.isDeleting) {
                    this.txt = fullTxt.substring(0, this.txt.length - 1);
                } else {
                    this.txt = fullTxt.substring(0, this.txt.length + 1);
                }

                this.el.innerHTML = '<span class="wrap">'+this.txt+'</span>';

                var that = this;
                var delta = 300 - Math.random() * 100;

                if (this.isDeleting) { delta /= 2; }

                if (!this.isDeleting && this.txt === fullTxt) {
                    delta = this.period;
                    this.isDeleting = true;
                } else if (this.isDeleting && this.txt === '') {
                    this.isDeleting = false;
                    this.loopNum++;
                    delta = 500;
                }

                setTimeout(function() {
                that.tick();
                }, delta);
            };

            window.onload = function() {
                var elements = document.getElementsByClassName('txt-rotate');
                for (var i=0; i<elements.length; i++) {
                    var toRotate = elements[i].getAttribute('data-rotate');
                    var period = elements[i].getAttribute('data-period');
                    if (toRotate) {
                      new TxtRotate(elements[i], JSON.parse(toRotate), period);
                    }
                }
                // INJECT CSS
                var css = document.createElement("style");
                css.type = "text/css";
                css.innerHTML = ".txt-rotate > .wrap { border-right: 0.08em solid #666 }";
                document.body.appendChild(css);
            };
        </script>
    </body>
</html>

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block title %} Home {% endblock %}

{% block content %}
<div class="container-fluid allblogs-div">
  <div class="container oc-screen">
      {% if messages %}
        <div class="row">
          <div class="col-md-6 mx-auto">
            {% for msg in messages %}
            <div class="alert alert-{{msg.level_tag}} custom-messages" role="alert">
                {{msg.message}}
            </div>
            {% endfor %}
          </div>
        </div>
      {% endif %}
      <div class="">
        <div class="row blog-main-heading-outer-div">
            <div class="blog-main-heading-inner-div">
                <h3 class="text-center">Blogs</h3>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="row equal">
                  {% for blog in blogs %}
                  <div class="col-md-4 col-sm-6 col-12">
                    <div class="card card-div">
                      <!-- <img class="card-img-top" src="{% static 'img/banner.jpg' %}" alt="Card image cap"> -->
                        <a href="{% url 'blog:blog_detail' id=blog.id slug=blog.blog_slug %}">
                            <div class="outer-div">
                                <div class="layer">{{blog.blog_title}}</div>
                                <div class="inner-div" style='background-image: url("{{blog.banner_image.url}}");'>

                                </div>
                            </div>
                        </a>
                        <div class="card-body">
                            <div class="blog-intro">
                              <span></span>
                              <small>By: <a href="{% url 'blog:filter_by_author' id=blog.blog_author.id %}">{{blog.blog_author|upper}}</a> &nbsp; On: <b>{{blog.created_on|date:"M d, Y"}}</b> </small><br><br>
                              <p>{{blog.blog_subtitle|truncatechars:30}}<a href="{% url 'blog:blog_detail' id=blog.id slug=blog.blog_slug %}" class="text-primary"> <b>Read Blog</b>
                              </a></p>
                              <p><a href="{% url 'blog:filter_by_category' category_slug=blog.blog_category.category_slug %}"><span class="badge badge-light blog-badge">{{blog.blog_category}}</span></a></p>
                            </div>
                        </div>
                      </div>
                  </div>
                  {% endfor %}
                </div>
            </div> <!-- End of left side blogs list container -->
        </div>
        <div class="row pagination-div">
            <div class="col-md-3 col-sm-6 mx-auto">
                {% if blogs.has_other_pages %}
                <ul class="pagination">
                    {% if blogs.has_previous %}
                        <li class="page-item">
                            <a href="?page={{ blogs.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}" class="page-link">
                                <i class="arrow-left">Previous</i>
                            </a>
                        </li>
                    {% else %}
                        <li class="page-item disabled"><a href="#!" class="page-link"><i class="arrow-left">Previous</i></a></li>
                    {% endif %}
                    {% for num in blogs.paginator.page_range %}
                        {% if blogs.number == num %}
                            <li class="page-item active"><a href="#!" class="page-link">{{ num }}</a></li>
                        {% else %}
                            <li class="page-item">
                                <a href="?page={{ num }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}" class="page-link">
                                    {{ num }}
                                </a>
                            </li>
                        {% endif %}
                    {% endfor %}
                    {% if blogs.has_next %}
                        <li class="page-item">
                            <a href="?page={{ blogs.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}" class="page-link">
                                <i class="arrow-right">Next</i></a></li>
                    {% else %}
                        <li class="page-item disabled">
                            <a href="#!" class="page-link">
                                <i class="arrow-right">Next</i>
                            </a>
                        </li>
                    {% endif %}
                </ul>
                {% endif %}
            </div>
        </div>
      </div>

  </div>
</div>
{% endblock %}

templates/notifications.html
notif

templates/pagenotfound.html
{% extends "base.html" %}
{% block title %} Page 404 {% endblock %}

{% block extra_css %}
<style type="text/css">
    .notfound {
        font-size: 70px;
        font-weight: bold;
        background: -webkit-linear-gradient(#eee, #333);
        background-color: #f38878;
        background-image: linear-gradient(45deg, #f37878, #78b8f3);
        background-size: 100%;
        -webkit-background-clip: text;
        -moz-background-clip: text;
        -webkit-text-fill-color: transparent;
        -moz-text-fill-color: transparent;
    }

    .notfound-info {
        font-size: 16px;
        font-weight: bold;
    }
</style>
{% endblock %}

{% block content %}
<div class="container">
  <div class="oc-screen">
    <div class="row">
        <div class="col-md-8 mx-auto">
            <h1 class="notfound text-center">404: PAGE NOT FOUND</h1>
            <p class="notfound-info text-center">Oopsy! The page you are looking for either got moved or you do not have access to it.</p>
        </div>
    </div>
  </div>
</div>
{% endblock %}